### ISSUE TITLE
typo in man

### ISSUE THREAD

**Issue by briling** [aoleynichenko/minichem#9]
an extra backslash!  (VERY important)
 https://github.com/aoleynichenko/minichem/blob/3fc68a3ecf883de699397b6d18e8735afec9aff2/docs/manual_ru.tex#L73

**Comment by aoleynichenko** [comment]
Ksenia, thank you very much!
If you are interested in the old minichem's code, I can send an archive with it to you. The old version doesn't use libint, integrals are evaluated by the hand-written Obara-Saika algorithm, the UHF method is implemented and the input format is much simpler (nwchem-like)...

**Comment by briling** [comment]
Thanks, I have my own :)
